[project]
name = "wire-rpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "msgspec>=0.21.1",
    "typing-extensions>=4.16.0",
]

[build-system]
requires = ["hatchling"]
build-requires = "hatchling"
build-backend = "hatchling.build"

[tool.mypy]
mypy_path = "."
packages = ["wire_rpc"]